### ISSUE TITLE
"Subversion Workspace Version" setting not taking effect

### ISSUE THREAD

**Issue by rakslice** [hudson2-plugins/subversion-plugin#42]
I've just set up a fresh install of Hudson 2.2.1, and with both the included subversion plugin 2.3.2 and the latest plugin 2.3.4, even though "Subversion Workspace Version" on the configuration screen is set to 1.4, the SVN plugin still produces checkouts where .svn/format is 12, indicating that the checkout is in 1.7 format.

**Comment by rakslice** [comment]
In the 2.3.0 subversion plugin under Hudson 2.2.0, the "Subversion Workspace Version" setting took effect as expected: setting it to 1.4 leads to .svn/format 8, and 1.5 leads to .svn/format 9.

**Comment by christ66** [comment]
This issue should be fixed in the latest version of the subversion-plugin (2.3.5).
